version: '2.1'

services:
  websms:
    image: websms
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    ## set your startup file here
    command: node --inspect app.js